apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-capstone1
  template:
    metadata:
      labels:
        app: devops-capstone1
    spec:
      containers:
      - name: app
        image: jayantdanech/devops-capstone-p1:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devops-capstone1-svc
spec:
  type: NodePort
  selector:
    app: devops-capstone1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
